# Generated by Django 5.2.4 on 2025-09-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('dep_name', models.CharField(max_length=150, unique=True, verbose_name='部门名称')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '禁用')], default=1, null=True, verbose_name='状态')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_department',
            },
        ),
    ]
