"""
Django settings for UniDjango project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

==========================================
配置说明 / Configuration Notes
==========================================
所有配置都可以通过环境变量覆盖，环境变量在根目录 .env 文件中定义。
Docker 容器启动时会自动读取 .env 文件中的配置。

主要配置项：
- DJANGO_SECRET_KEY: Django 密钥
- DJANGO_ALLOWED_HOSTS: 允许访问的主机
- DJANGO_TIME_ZONE: 时区
- DJANGO_LANGUAGE_CODE: 语言
- DB_HOST: 数据库主机
- MYSQL_DATABASE: 数据库名
- MYSQL_ROOT_PASSWORD: 数据库密码
- DEBUG: 调试模式
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ==========================================
# 安全配置 / Security Configuration
# ==========================================
# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取，如果没有则使用默认值（仅用于开发）
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Swagger / ReDoc 仅在调试模式开启；生产环境不暴露接口文档。
SWAGGER_ENABLED = DEBUG

# 生产环境必须提供独立密钥，开发环境才允许回退到不安全密钥。
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-me'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY 环境变量未设置')

# 允许访问的主机，从环境变量读取，支持逗号分隔的多个值
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

# 生产环境禁止使用通配符，否则 Host 头可被任意注入，污染头像/文件等绝对 URL。
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('生产环境不允许 DJANGO_ALLOWED_HOSTS 为 *，请配置明确的域名/IP')

# JWT 签名密钥：与 Django SECRET_KEY 分离，便于独立轮换、降低泄露面。
JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', '')
if not JWT_SECRET_KEY:
    if DEBUG:
        JWT_SECRET_KEY = SECRET_KEY  # 仅开发环境回退
    else:
        raise ImproperlyConfigured('JWT_SECRET_KEY 环境变量未设置')

# 可信反向代理层数：用于正确解析客户端真实 IP（生产 Nginx 前为 1 层）。
TRUSTED_PROXY_COUNT = int(os.environ.get('TRUSTED_PROXY_COUNT', '0') or 0)


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 认证体系说明：用户身份统一由自定义 SysUser + JWT 中间件处理，不使用 Django 的
    # 会话登录。这里保留 auth/contenttypes 仅为复用密码哈希与强度校验工具
    # （django.contrib.auth.hashers / password_validation），不参与请求认证流程。
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',  #用户模块配置
    'menu.apps.MenuConfig',  #菜单模块配置
    'role.apps.RoleConfig',  #角色模块配置
    'department.apps.DepartmentConfig',  #部门模块配置
    'log.apps.LogConfig',  #日志监控模块配置
    'rest_framework',  # Django REST framework
    'corsheaders',  #  跨域请求处理
    'django_filters',  # Django过滤器支持
    'drf_yasg',  # Swagger文档生成
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨域中间件,必须放在第一位
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  #去掉csrf
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'log.middleware.RequestLogMiddleware', # 请求日志中间件
    'user.middleware.JwtAuthenticationMiddleware',  # JWT_TOKEN 认证中间件（唯一认证入口）
]


# 跨域相关配置
CORS_ORIGIN_ALLOW_ALL = os.environ.get('CORS_ORIGIN_ALLOW_ALL', 'False').lower() in ('true', '1', 'yes')
CORS_ALLOWED_ORIGINS = [
    h.strip()
    for h in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if h.strip()
]
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'False').lower() in ('true', '1', 'yes')
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'DELETE', 'PATCH',  # 允许的HTTP方法
]

# CSRF 配置
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:9528',
#     'http://127.0.0.1:9528',
# ]



ROOT_URLCONF = 'UniDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'UniDjango.wsgi.application'


# ==========================================
# 数据库配置 / Database Configuration
# ==========================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 所有数据库配置都从环境变量读取，默认值用于本地开发

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'unidjango'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD', 'change-me'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('MYSQL_INTERNAL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持 Emoji 和特殊字符
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================================
# 国际化配置 / Internationalization
# ==========================================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'zh-hans')

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Asia/Shanghai')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# Django REST Framework 配置
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # 启用django-filter过滤后端
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.PreAuthenticatedAuthentication', # 使用中间件认证的结果
    ], 
    'DEFAULT_PERMISSION_CLASSES': [
        'utils.permissions.IsAuthenticated', # 默认要求登录，视图可单独调整
    ],
}

# ==========================================
# 媒体文件配置 / Media Files
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# Redis 缓存配置 / Redis Cache Configuration
# ==========================================
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'PASSWORD': REDIS_PASSWORD,
        },
        'KEY_PREFIX': 'ylf',
        'TIMEOUT': 300,  # 默认缓存超时 5 分钟
    }
}

# 关闭自动追加斜杠，避免无斜杠的 PUT/PATCH/POST 被强制重定向到带斜杠 URL
APPEND_SLASH = False
