# Generated by Django 5.2.4 on 2025-08-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父菜单ID')),
                ('order_num', models.IntegerField(null=True, verbose_name='排序号')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='菜单路径')),
                ('component', models.CharField(max_length=200, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=20, null=True, verbose_name='菜单类型')),
                ('perms', models.CharField(max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.sysmenu', verbose_name='菜单ID')),
            ],
            options={
                'verbose_name': '角色菜单关联表',
                'verbose_name_plural': '角色菜单关联表',
                'db_table': 'sys_role_menu',
            },
        ),
    ]
