# Generated by Django 5.2.4 on 2025-07-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮件')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='电话号码')),
                ('login_date', models.DateField(null=True, verbose_name='最后登录时间')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '禁用')], default=1, null=True, verbose_name='状态')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
