# Generated by Django 5.2.4 on 2025-09-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('user', '0002_sysuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.sysrole', verbose_name='角色'),
        ),
    ]
