# Generated by Django 5.2.4 on 2025-09-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sysuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='role',
        ),
    ]
