# Generated by Django 5.1.4 on 2026-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_sysuser_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
