# Generated by Django 5.2.4 on 2025-08-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='角色编码')),
                ('create_time', models.DateField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(null=True, verbose_name='更新时间')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.sysrole', verbose_name='角色ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysuser', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户角色关联表',
                'verbose_name_plural': '用户角色关联表',
                'db_table': 'sys_user_role',
            },
        ),
    ]
