# Generated by Django 5.1.4 on 2026-09-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_datetime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='remark',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sysuserrole',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
