# Generated by Django 5.2.4 on 2025-12-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_sysuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('ip', models.CharField(max_length=50, null=True, verbose_name='访问IP')),
                ('method', models.CharField(max_length=10, null=True, verbose_name='请求方式')),
                ('path', models.CharField(max_length=255, null=True, verbose_name='请求路径')),
                ('params', models.TextField(null=True, verbose_name='请求参数')),
                ('status', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('cost_time', models.FloatField(null=True, verbose_name='耗时(ms)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('log_type', models.CharField(default='INFO', max_length=10, verbose_name='日志类型')),
                ('error_msg', models.TextField(null=True, verbose_name='错误信息')),
                ('traceback', models.TextField(null=True, verbose_name='堆栈详情')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.sysuser', verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'sys_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
